[theme]
base = "light"
primaryColor = "#111827"
backgroundColor = "#FAF9F6"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#111827"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
